name: Course Marketplace CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/OnlineCourseMarketPlace_Backend/OnlineCourseMarketPlace_Backend

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore NuGet packages
        run: dotnet restore YoutubeWebApi.sln

      - name: Build Solution
        run: dotnet build YoutubeWebApi.sln --configuration Release --no-restore

      - name: Publish YoutubeWebApi
        run: dotnet publish YoutubeWebApi/YoutubeWebApi.csproj -c Release -o publish

  frontend:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/OnlineCourseMarketPlace_Frontend/frontend

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: frontend/OnlineCourseMarketPlace_Frontend/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build React
        run: npm run build